// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerLeagueManagement;

#nullable disable

namespace Module.SoccerLeagueManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SoccerLeagueDbContext))]
    partial class SoccerLeagueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerSoccerGame", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SoccerGameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerId", "SoccerGameId");

                    b.HasIndex("SoccerGameId");

                    b.ToTable("PlayerSoccerGame");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerSoccerLeague", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SoccerLeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerId", "SoccerLeagueId");

                    b.HasIndex("SoccerLeagueId");

                    b.ToTable("PlayerSoccerLeague");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerStadium", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerId", "StadiumId");

                    b.HasIndex("StadiumId");

                    b.ToTable("PlayerStadium");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerTeam", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerTeam");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntitySoccerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("LocalTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalTeamGoals")
                        .HasColumnType("int");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<string>("VisitingTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitingTeamGoals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SoccerGame");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntitySoccerLeague", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoccerLeague");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityStadium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stadium");
                });

            modelBuilder.Entity("SoccerLeagueManagement.DBModels.EntityPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayingPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("SoccerLeagueManagement.DBModels.EntityTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerSoccerGame", b =>
                {
                    b.HasOne("SoccerLeagueManagement.DBModels.EntityPlayer", "EntityPlayer")
                        .WithMany("PlayerSoccerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.SoccerLeagueManagement.Shared.DbModels.EntitySoccerGame", "EntitySoccerGame")
                        .WithMany("PlayerSoccerGames")
                        .HasForeignKey("SoccerGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityPlayer");

                    b.Navigation("EntitySoccerGame");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerSoccerLeague", b =>
                {
                    b.HasOne("SoccerLeagueManagement.DBModels.EntityPlayer", "EntityPlayer")
                        .WithMany("PlayerSoccerLeagues")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.SoccerLeagueManagement.Shared.DbModels.EntitySoccerLeague", "EntitySoccerLeague")
                        .WithMany("PlayerSoccerLeagues")
                        .HasForeignKey("SoccerLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityPlayer");

                    b.Navigation("EntitySoccerLeague");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerStadium", b =>
                {
                    b.HasOne("SoccerLeagueManagement.DBModels.EntityPlayer", "EntityPlayer")
                        .WithMany("PlayerStadiums")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.SoccerLeagueManagement.Shared.DbModels.EntityStadium", "EntityStadium")
                        .WithMany("PlayerStadiums")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityPlayer");

                    b.Navigation("EntityStadium");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityPlayerTeam", b =>
                {
                    b.HasOne("SoccerLeagueManagement.DBModels.EntityPlayer", "EntityPlayer")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerLeagueManagement.DBModels.EntityTeam", "EntityTeam")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityPlayer");

                    b.Navigation("EntityTeam");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntitySoccerGame", b =>
                {
                    b.Navigation("PlayerSoccerGames");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntitySoccerLeague", b =>
                {
                    b.Navigation("PlayerSoccerLeagues");
                });

            modelBuilder.Entity("Module.SoccerLeagueManagement.Shared.DbModels.EntityStadium", b =>
                {
                    b.Navigation("PlayerStadiums");
                });

            modelBuilder.Entity("SoccerLeagueManagement.DBModels.EntityPlayer", b =>
                {
                    b.Navigation("PlayerSoccerGames");

                    b.Navigation("PlayerSoccerLeagues");

                    b.Navigation("PlayerStadiums");

                    b.Navigation("PlayerTeams");
                });

            modelBuilder.Entity("SoccerLeagueManagement.DBModels.EntityTeam", b =>
                {
                    b.Navigation("PlayerTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
